# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testlab.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'testlab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtestlab.proto\x12\x07testlab\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"!\n\x10\x42lacklistRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"-\n\x0cUserResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x11\x42lacklistResponse\x12\x0f\n\x07\x62locked\x18\x01 \x01(\x08\x32\x45\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.testlab.UserRequest\x1a\x15.testlab.UserResponse2[\n\x10\x42lacklistService\x12G\n\x0e\x43heckBlacklist\x12\x19.testlab.BlacklistRequest\x1a\x1a.testlab.BlacklistResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testlab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=26
  _globals['_USERREQUEST']._serialized_end=54
  _globals['_BLACKLISTREQUEST']._serialized_start=56
  _globals['_BLACKLISTREQUEST']._serialized_end=89
  _globals['_USERRESPONSE']._serialized_start=91
  _globals['_USERRESPONSE']._serialized_end=136
  _globals['_BLACKLISTRESPONSE']._serialized_start=138
  _globals['_BLACKLISTRESPONSE']._serialized_end=174
  _globals['_USERSERVICE']._serialized_start=176
  _globals['_USERSERVICE']._serialized_end=245
  _globals['_BLACKLISTSERVICE']._serialized_start=247
  _globals['_BLACKLISTSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
