# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import testlab_pb2 as testlab__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in testlab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/testlab.UserService/GetUser',
                request_serializer=testlab__pb2.UserRequest.SerializeToString,
                response_deserializer=testlab__pb2.UserResponse.FromString,
                _registered_method=True)


class UserServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=testlab__pb2.UserRequest.FromString,
                    response_serializer=testlab__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testlab.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testlab.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testlab.UserService/GetUser',
            testlab__pb2.UserRequest.SerializeToString,
            testlab__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BlacklistServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBlacklist = channel.unary_unary(
                '/testlab.BlacklistService/CheckBlacklist',
                request_serializer=testlab__pb2.BlacklistRequest.SerializeToString,
                response_deserializer=testlab__pb2.BlacklistResponse.FromString,
                _registered_method=True)


class BlacklistServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckBlacklist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlacklistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBlacklist': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBlacklist,
                    request_deserializer=testlab__pb2.BlacklistRequest.FromString,
                    response_serializer=testlab__pb2.BlacklistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testlab.BlacklistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testlab.BlacklistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlacklistService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckBlacklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testlab.BlacklistService/CheckBlacklist',
            testlab__pb2.BlacklistRequest.SerializeToString,
            testlab__pb2.BlacklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
